### ISSUE TITLE
Custom Context Propogation

### ISSUE THREAD

**Issue by krshna-dtdl** [micrometer-metrics/context-propagation#107]
I have a requirement where I need to save the current traceId information in a database. After a few minutes, a job will pick a task and that task needs to have the same traceId with a diff span id.

How can I do that? I am using Spring 3 with Micrometer.

**Comment by chemicL** [comment]
Please consider using Micrometer's Slack or stackoverflow.com to ask questions:
https://slack.micrometer.io/

The issue tracker is for bug reports / enhancement ideas.
