### ISSUE TITLE
Update documentation to reference ContextSnapshotFactory

### ISSUE THREAD

**Issue by philsttr** [micrometer-metrics/context-propagation#118]
The [current example in the documentation](https://micrometer.io/docs/contextPropagation#_usage_examples) uses `ContextSnapshot.captureAllUsing(key -> true, registry)`, which was recently deprecated in #105 

Please update the example to use non-deprecated methods, and describe usage of the recently introduced `ContextSnapshotFactory` in documentation where appropriate.

**Comment by marcingrzejszczak** [comment]
fixed via https://github.com/micrometer-metrics/micrometer-docs/commit/a5d5960099a2aafefed2ee34286141eb432fa153
