### ISSUE TITLE
Restore of `ThreadLocalAccessors` should be called in the opposite order than the setters

### ISSUE THREAD

**Issue by dstepanov** [micrometer-metrics/context-propagation#130]
The order should be:
- `MyThreadLocalAccessorsA` set
- `MyThreadLocalAccessorsB` set
- `MyThreadLocalAccessorsB` restore
- `MyThreadLocalAccessorsA` restore

In our case, our internal `ThreadLocalAccessors` is opening observation scopes and doesn't have a change to close it before `ObservationThreadLocalAccessor`.

**Comment by jonatan-ivanov** [comment]
Fixed via https://github.com/micrometer-metrics/context-propagation/pull/131
