### ISSUE TITLE
OutOfMemory exception using context-propagation

### ISSUE THREAD

**Issue by imosapatryk** [micrometer-metrics/context-propagation#148]
Hi,
I have been testing Spring WebFlux and context-propagation library. 

Spring Boot 3.0.7
Reactor 3.5.3
context-propagation 1.0.4

I have used the `contextWrite` operation in WebFilter to populate `MDC context` and `SecurityContext`. I also have used the `Hooks.enableAutomaticContextPropagation` with implementation of `ThreadLocalAccessors`. 

I can see that this object below

`io.micrometer.observation.SimpleObservation$SimpleScope	24,739,328 B (11.5%)	773,104 (18.8%)`

consumes a lot of memory and many instances are created, we receive OutOfMemory exception after some time of processing (50 threads sending requests from JMeter), and we think this libarary causes the problems on context snapshot.

```
public class SecurityContextThreadLocalAccessor implements ThreadLocalAccessor<SecurityContext> {

    public static final String KEY = "securityContext";

    @Override
    public Object key() {
        return KEY;
    }

    @Override
    public SecurityContext getValue() {
        return SecurityContextHolder.get();
    }

    @Override
    public void setValue( SecurityContext value ) {
        SecurityContextHolder.set( value );
    }

    @Override
    public void setValue() {
        SecurityContextHolder.clear();
    }

    @Override
    public void reset() {
        SecurityContextHolder.clear();
    }
}
```
and MDC:

```
public class MdcThreadLocalAccessor implements ThreadLocalAccessor<Map<String, String>> {

    public static final String KEY = "mdc";

    @Override
    public Object key() {
        return KEY;
    }

    @Override
    public Map<String, String> getValue() {
        return MDC.getCopyOfContextMap();
    }

    @Override
    public void setValue( Map<String, String> value ) {
        MDC.setContextMap( value );
    }

    @Override
    public void setValue() {
        MDC.clear();
    }

    @Override
    public void reset() {
        setValue();
    }
}
```

Do you guys have any idea of what could be the problem?

**Comment by marcingrzejszczak** [comment]
Can you actually confirm that this is not a problem with Spring Security? If you move Spring Security out of the equation can you confirm that the memory usage is big? I'm asking this cause AFAIK there are some issues with Spring Security and Context Propagation.

**Comment by imosapatryk** [comment]
The `SecurityContextHolder` is my own implementation that is populated in WebFilter:

```
    private final ThreadLocal<SecurityContext> securityContexts = new ThreadLocal<>();

    @Override
    public SecurityContext get() {
        return securityContexts.get();
    }

    @Override
    public void set( SecurityContext securityContext ) {
        securityContexts.set( securityContext );
    }

    @Override
    public void clear() {
        securityContexts.remove();
    }
```
We don't use Spring Security (only spring-security-crypto or rsa in our spring cloud dependencies)

**Comment by marcingrzejszczak** [comment]
@chemicL maybe this is related to what I've shown you recently which is the number of scopes created for a single request?

@imosapatryk what are your JVM settings that you run out of memory? Also you're running 50 threads at the same time so no wonder you have bigger memory usage.

With `Hooks.enableAutomaticContextPropagation` it will create A LOT of scopes and that's normal. If you don't want that to happen just don't enable automatic context propagation or increase the JVM memory settings :shrug:

**Comment by imosapatryk** [comment]
I use the same memory size as for the servlet application. I exepected with WebFlux to use a bit less resources comparing to classic application due to less threads and context switching.

I was also wondering if is not better if application would slow down a bit instead of exploading the whole application?

**Comment by chemicL** [comment]
Can you please start with updating the dependencies to the latest versions?

```
Spring Boot 3.0.7 -> either 3.0.11 or 3.1.4
Reactor 3.5.3 -> 3.5.10
context-propagation 1.0.4 -> 1.0.5
```

1. Then, rerun and see if the problem persists.
2. Then, remove the security context accessor and see if the problem still occurs.
3. If it does, please provide a reproducer and we can analyse.
4. If the problem is with the security context accessor, then it's something to dig deeper into on your end.

Let us know.

**Comment by chemicL** [comment]
With that I think it's best to know the versions of micrometer and micrometer-tracing that you are using. Perhaps they're also outdated? If, using the latest versions you still observe the issue, please open a ticket in micrometer or micrometer-tracing repository.

**Comment by imosapatryk** [comment]
You are right, I checked the dependency tree & effective pom. Some of my assets were overriding the micrometer version, so the observation scopes were not closed. I can confirm it started working using micrometer 1.11.4. Thank you guys for your support.
