### ISSUE TITLE
MdcThreadLocalAccessor for SLF4J

### ISSUE THREAD

**Issue by chemicL** [micrometer-metrics/context-propagation#191]
As suggested in https://github.com/spring-projects/spring-boot/issues/39299, it feels reasonable to create a new utility module for SLF4J with a `ThreadLocalAccessor` (TLA) that allows interacting with the `MDC` during `Thread` hops. I propose two implementations:
- [global `MDC` TLA](https://gist.github.com/chemicL/0e0d8e95e28414f0ecb769a5b8ca326e#file-testmdc-java-L32-L55), which copies and overrides the entire contents of `MDC` -> should only be used when the user is certain no other accessor uses the `MDC`
- [key-based `MDC` TLA](https://gist.github.com/chemicL/0e0d8e95e28414f0ecb769a5b8ca326e?permalink_comment_id=4569586#gistcomment-4569586), which only transports specified entries across `Thread` boundaries.

@ttddyy, @rstoyanchev @marcingrzejszczak @wilkinsona does this sound ok?

**Comment by rstoyanchev** [comment]
What about just an additional package in the same module as an optional compile-only dependency?

**Comment by chemicL** [comment]
@rstoyanchev that's a good idea. I'm going in this direction.

I have a design consideration at this point for the key-based approach. There are two options when it comes to the API:

## Approach 1: Accept a list of keys of type String

Pros:
* saves on copying the contents of MDC upon every access because we just select the given keys
* saves memory and CPU
* it's easier to provide a List of Strings than to provide a Predicate

Cons:
* inflexible - families of keys can't be selected this way

## Approach 2: Accept a Predicate<String> to determine which 

Pros:
* very flexible, can allow to select a family of keys that for instance share a prefix

Cons:
* every access requires to copy the MDC map in order to traverse all the keys which is not very performant
* waste of memory and CPU time

I'd love some feedback before pushing a PR.

**Comment by chemicL** [comment]
I think I'll go with Approach 1. If a more flexible approach is required, the users can implement such an accessor based on how the list-based approach is implemented.

Regarding my concern:

>when someone explicitly provides a Map for some `ContextAccessor` that has entries which would have been filtered out during ThreadLocal capture, we either apply the filtering when setting the values or we skip filtering, which can lead to unexpected results

It actually applies to both approaches and I'll filter out keys that don't match both in the restoring and in capturing passes.

**Comment by chemicL** [comment]
Resolved by #194
