### ISSUE TITLE
Risks of runtime type variance of ContextRegistry's ContextAccessor instances

### ISSUE THREAD

**Issue by chemicL** [micrometer-metrics/context-propagation#33]
The current API of `ContextRegistry` imposes some risks by the way registration and retrieval is performed with regards to accepted `ContextAccessor` instances implementation.

https://github.com/chemicL/context-propagation/commit/ca7ca4798016180744e11895fc4c33d85d5be0c3 shows two potential risks:
- replacing an existing accessor for different context type with common base type due to type erasure
- having two different accessors, but using the wrong one in case of declared support for base type instead of the concrete context type

There are more possible, but that's just to highlight some risks.

These situations could result in runtime failures (NPE, unexpected behavior). The reason for it is the runtime variance caused by the asymmetry of registration identity being based on the `ContextAccessor` runtime `Class` vs the access for both reading and writing being performed upon a list of `ContextAccessor`s claimed supported types using `boolean canReadFrom(Class<?> contextType)` or `boolean canWriteTo(Class<?> contextType)` at runtime.

The risk described here is rather low and it might not be a practical situation where base context type is shared between various libraries.

However, this risk can be avoided by making `ContextRegistry` expose two registration steps:
- one for registering a reader of specific context type,
- another for registering a writer of specific context type,
- both assuming an API change of `ContextAccessor`: instead of the boolean canWriteTo/canReadFrom methods, replacing them with `Class<?> readType()` and `Class<?> writeType()` and using a equality comparison instead of `Class::isAssignableFrom()` which the current implementations are free to use, increasing the risk surface.

Both should be used with a single instance of `ContextAccessor`, but that would separate the identity concern from `ContextAccessor` actual `Class` at runtime, instead using the handled context type at runtime. Collision detection can be made at registration time, allowing to fail fast or log a warning.

The `ContextRegistry` implementations could then either use two lists or store the accessors in `Map<Class<?>, ContextAccessor<?, ?>`.

**Comment by rstoyanchev** [comment]
Superseded by #35.
